project:
  type: website
  output-dir: .

website:
  title: "PHYS 301"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://phys301.github.io/Winter2025/
        text: "Winter 2025" 
        target: _blank #makes it open in new page

format:
  html:
    theme: flatly
    css: styles.css

editor: visual
self-contained: true



